### ISSUE TITLE
[Enhancement] : the twitter logo is not updated

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [OWASP/wrongsecrets-ctf-party#423]
The logo of the twitter is not 
It is the previous logo that was used by twitter before.

Expected behaviors
The logo of the twitter should be updated .

**Comment by commjoen** [comment]
I don't recognize the screenshot yet. Feel free to contact us through Slack so we can have a chat about the logo and the problems you are encountering.

**Comment by commjoen** [comment]
Ah I found the place! It is at the bottom of https://owasp.org/www-project-wrongsecrets/ right? Unfortunately this is something that cannot be fixed in this project/repo. It is part of the OWASP website itself, which we do not control. I will flag this with @hblankenship who is managing this.
Closing this issue as it is not part of our own project.
